name: 'check'
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          registry-url: https://npm.pkg.github.com/
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run check
        run: npm run check